# Preparing the dataset for hippocampus segmentation

In this notebook you will use the skills and methods that we have talked about during our EDA Lesson to prepare the hippocampus dataset using Python. Follow the Notebook, writing snippets of code where directed so using Task comments, similar to the one below, which expects you to put the proper imports in place. Write your code directly in the cell with TASK comment. Feel free to add cells as you see fit, but please make sure that code that performs that tasked activity sits in the same cell as the Task comment.


In [1]:
# TASK: Import the following libraries that we will use: nibabel, matplotlib, numpy
import nibabel as nib
import os
import numpy as np
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import itertools

It will help your understanding of the data a lot if you were able to use a tool that allows you to view NIFTI volumes, like [3D Slicer](https://www.slicer.org/). I will refer to Slicer throughout this Notebook and will be pasting some images showing what your output might look like.

## Loading NIFTI images using NiBabel

NiBabel is a python library for working with neuro-imaging formats (including NIFTI) that we have used in some of the exercises throughout the course. Our volumes and labels are in NIFTI format, so we will use nibabel to load and inspect them.

NiBabel documentation could be found here: https://nipy.org/nibabel/

Our dataset sits in two directories - *images* and *labels*. Each image is represented by a single file (we are fortunate to have our data converted to NIFTI) and has a corresponding label file which is named the same as the image file.

Note that our dataset is "dirty". There are a few images and labels that are not quite right. They should be quite obvious to notice, though. The dataset contains an equal amount of "correct" volumes and corresponding labels, and you don't need to alter values of any samples in order to get the clean dataset.

In [2]:
# TASK: Your data sits in directory /data/TrainingSet.
# Load an image and a segmentation mask into variables called image and label
image = nib.load("/Users/taruntalreja/Desktop/data/TrainingSet/images/hippocampus_001.nii.gz")
print(image.shape)
label = nib.load("/Users/taruntalreja/Desktop/data/TrainingSet/labels/hippocampus_001.nii.gz")
print(label.shape)

(35, 51, 35)
(35, 51, 35)


In [3]:
# Nibabel can present your image data as a Numpy array by calling the method get_fdata()
# The array will contain a multi-dimensional Numpy array with numerical values representing voxel intensities. 
# In our case, images and labels are 3-dimensional, so get_fdata will return a 3-dimensional array. You can verify this
# by accessing the .shape attribute. What are the dimensions of the input arrays?

# TASK: using matplotlib, visualize a few slices from the dataset, along with their labels. 
# You can adjust plot sizes like so if you find them too small:
# plt.rcParams["figure.figsize"] = (10,10)
def show_slices(slices):
	""" Function to display row of image slices """
	fig, axes = plt.subplots(1, len(slices))
	for i, slice in enumerate(slices):
		axes[i].imshow(slice.T, cmap="gray", origin="lower")

slice_a = label.get_fdata()[26, :, :]
slice_b =  label.get_fdata()[:, 30, :]
slice_c =  label.get_fdata()[:, :, 16]
show_slices([slice_a, slice_b, slice_c])
plt.suptitle("Label Slices")  
plt.show()

In [4]:
slice_a = image.get_fdata()[26, :, :]
slice_b =  image.get_fdata()[:, 30, :]
slice_c =  image.get_fdata()[:, :, 16]
show_slices([slice_a, slice_b, slice_c])
plt.suptitle("Image Slices")  
plt.show()

print(image.get_fdata())
print(image.get_fdata().shape)

[[[ 42.  29.  28. ...  95. 100.  98.]
  [ 37.  30.  27. ... 101. 100.  97.]
  [ 30.  27.  27. ... 101.  99.  99.]
  ...
  [101.  93.  90. ...  28.  34.  35.]
  [ 92.  88.  84. ...  41.  39.  44.]
  [ 63.  65.  60. ...  43.  45.  54.]]

 [[ 39.  30.  33. ... 101. 101. 100.]
  [ 38.  30.  31. ... 103. 100. 101.]
  [ 42.  29.  28. ... 103. 106. 100.]
  ...
  [100. 100. 102. ...  22.  33.  36.]
  [ 98.  99. 105. ...  26.  36.  41.]
  [ 91.  90.  90. ...  29.  38.  44.]]

 [[ 43.  35.  38. ... 110. 110.  98.]
  [ 49.  35.  36. ... 105. 106. 100.]
  [ 43.  30.  34. ... 102. 105.  99.]
  ...
  [ 67.  84.  96. ...  17.  27.  35.]
  [ 81.  94.  93. ...  14.  29.  37.]
  [ 98. 102.  97. ...  28.  30.  36.]]

 ...

 [[ 82.  81.  79. ...   8.  12.  18.]
  [ 84.  78.  81. ...   9.  12.  16.]
  [ 81.  81.  81. ...  12.  20.  34.]
  ...
  [ 47.  45.  47. ...  50.  37.  32.]
  [ 38.  36.  37. ...  50.  44.  41.]
  [ 46.  47.  40. ...  52.  50.  51.]]

 [[ 91.  89.  87. ...   7.   5.   6.]
  [ 91.  90.

Load volume into 3D Slicer to validate that your visualization is correct and get a feel for the shape of structures.Try to get a visualization like the one below (hint: while Slicer documentation is not particularly great, there are plenty of YouTube videos available! Just look it up on YouTube if you are not sure how to do something)

![3D slicer](img/Slicer.png)

In [5]:
# Stand out suggestion: use one of the simple Volume Rendering algorithms that we've
# implemented in one of our earlier lessons to visualize some of these volumes

A = label.get_fdata()

dimension1 = np.sum(A, axis = 0)
fig = plt.figure()
axis0 = fig.add_subplot(121)
axis0.imshow(dimension1)
plt.show()

fig = plt.figure()
dimension2 = np.sum(A, axis = 1)
axis1 = fig.add_subplot(121)
axis1.imshow(dimension2)
plt.show()

dimension3 = np.sum(A, axis = 2)
fig = plt.figure()
axis2 = fig.add_subplot(121)
axis2.imshow(dimension3)
plt.show()

In [6]:
img=mpimg.imread('/home/workspace/img/Slicer.png')
imgplot = plt.imshow(img)
plt.show()

IOError: [Errno 2] No such file or directory: '/home/workspace/img/Slicer.png'

## Looking at single image data
In this section we will look closer at the NIFTI representation of our volumes. In order to measure the physical volume of hippocampi, we need to understand the relationship between the sizes of our voxels and the physical world.

In [7]:
# Nibabel supports many imaging formats, NIFTI being just one of them. I told you that our images 
# are in NIFTI, but you should confirm if this is indeed the format that we are dealing with
# TASK: using .header_class attribute - what is the format of our images?
# Slicer Render slicer image is based on below youtube video: 
# https://www.youtube.com/watch?v=MKLWzD0PiIc
# img = mpimg.imread('slicer_render.png')
# imgplot = plt.imshow(img)
# plt.show()
print(image.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : 
db_name         : 
extents         : 0
session_error   : 0
regular         : r
dim_info        : 0
dim             : [ 3 35 51 35  1  1  1  1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : uint8
bitpix          : 8
slice_start     : 0
pixdim          : [1. 1. 1. 1. 1. 0. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : 5.0.10
aux_file        : none
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : 1.0
qoffset_y       : 1.0
qoffset_z       : 1.0
srow_x          : [1. 0. 0. 1.]
srow_y          : [0. 1. 0. 1.]
srow_

Further down we will be inspecting .header attribute that provides access to NIFTI metadata. You can use this resource as a reference for various fields: https://brainder.org/2012/09/23/the-nifti-file-format/

In [8]:
# TASK: How many bits per pixel are used?
# 8

# TASK: What are the units of measurement?
# xyzt_units

# TASK: Do we have a regular grid? What are grid spacings?
# The grid spacings is as follows:   
# [1. 1. 1. 1. 1. 0. 0. 0.]

# TASK: What dimensions represent axial, sagittal, and coronal slices? How do you know?
# Affine attribute gives us information about the affine
# Affine: array-like or None, optional. Affine transform for the data. 
# This is used to determine how the data should be sliced for plotting into the 
# sagittal, coronal, and axial view axes. If None, identity is assumed. 
# The aspect ratio of the data are inferred from the affine transform.



In [9]:
np.set_printoptions(precision=3, suppress=True)

# Print the affine
print(image.affine)

print(nib.affines.voxel_sizes(label.affine))

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
[1. 1. 1.]


In [10]:
# By now you should have enough information to decide what are dimensions of a single voxel
# TASK: Compute the volume (in mm³) of a hippocampus using one of the labels you've loaded. 
# You should get a number between ~2200 and ~4500
all_volumes=list()
volume = 0

sliced_labels = [[f,nib.load(os.path.join("/Users/taruntalreja/Desktop/data/TrainingSet/labels/", f))] 
                for f in os.listdir("/Users/taruntalreja/Desktop/data/TrainingSet/labels/")]

def getVolume(label):
    vol = 0
    for i in range(label.shape[0]):
        for j in range(label.shape[1]):
            for k in range(label.shape[2]):
                if (label[i][j][k]) != 0:
                    vol += 1
    return vol

for idx in range(260): # 260 slices
    t_label = sliced_labels[idx][1].get_fdata()
    vol = getVolume(t_label)
    all_volumes.append(vol)

nonoutlier_volumes = np.array([v for v in all_volumes if (v<4500 and v>2200)])
print(nonoutlier_volumes)



[4151 3536 2873 2382 3654 3222 3442 3095 3686 3455 2956 2618 2930 2753
 2451 3377 3724 3575 3113 3327 2863 2857 3994 3361 3208 3172 3445 3248
 3568 3814 3229 2920 2819 3000 3356 3869 3660 3946 3372 3918 3845 3847
 2697 3409 3423 3088 3831 3160 2714 3027 3478 3219 3000 3947 2943 3439
 3304 3516 3109 3997 3707 3165 2570 2535 2755 3823 2684 3785 3450 3661
 2588 3450 2870 3594 2948 3420 3435 3195 2613 3257 3127 3412 3479 3326
 2726 3292 3522 2546 3061 3983 3325 2980 3987 3623 2590 3349 2678 3371
 3216 2863 3856 3105 4071 2995 3773 3689 3335 3957 3671 3692 2593 3089
 2920 2634 3820 3742 2708 3582 3506 3534 3404 3146 3409 3353 3923 3456
 3220 2471 3658 3167 3252 3749 3600 3733 2945 3272 2629 3450 2416 2859
 3704 3622 2593 3718 4263 3092 3650 3023 3700 3285 3080 3519 3202 3628
 2714 3763 2950 2448 3340 4383 3374 3878 3150 3167 3605 2635 3431 2942
 2757 2704 3029 3979 3285 3102 3877 2665 3612 3575 3679 2890 2647 3194
 3210 2894 3502 4029 3581 3643 4401 3054 3333 3842 2830 2422 4074 2811
 3698 

## Plotting some charts

In [13]:
# TASK: Plot a histogram of all volumes that we have in our dataset and see how 
# our dataset measures against a slice of a normal population represented by the chart below.
plt.hist(all_volumes, bins=10)
plt.show()

plt.hist(nonoutlier_volumes, bins=10)
plt.show()

<img src="img/nomogram_fem_right.svg" width=400 align=left>

Do you see any outliers? Why do you think it's so (might be not immediately obvious, but it's always a good idea to inspect) outliers closer. If you haven't found the images that do not belong, the histogram may help you.

In the real world we would have precise information about the ages and conditions of our patients, and understanding how our dataset measures against population norm would be the integral part of clinical validation that we talked about in last lesson. Unfortunately, we do not have this information about this dataset, so we can only guess why it measures the way it is. If you would like to explore further, you can use the [calculator from HippoFit project](http://www.smanohar.com/biobank/calculator.html) to see how our dataset compares against different population slices

Did you notice anything odd about the label files? We hope you did! The mask seems to have two classes, labeled with values `1` and `2` respectively. If you visualized sagittal or axial views, you might have gotten a good guess of what those are. Class 1 is the anterior segment of the hippocampus and class 2 is the posterior one. 

For the purpose of volume calculation we do not care about the distinction, however we will still train our network to differentiate between these two classes and the background

In [11]:
def resize_data(input, s1, s2, s3):
	a, b, c = input.shape[0:3]

	new_a = s1
	new_b = s2
	new_c = s3

	delta_x = a / new_a
	delta_y = b / new_b
	delta_z = c / new_c

	updated_input = np.zeros((new_a, new_b, new_c))

	for i, j, k in itertools.product(range(new_a), range(new_b),range(new_c)):
		updated_input[i][j][k] = input.get_fdata()[int(i * delta_x)][int(j * delta_y)][int(k * delta_z)]

	return updated_input

In [13]:
# TASK: Copy the clean dataset to the output folder inside section1/out. You will use it in the next Section
path1 = "/data/TrainingSet/images/"
path2 = "/data/TrainingSet/labels/"
images = os.listdir(path1)

for image in images:
    co0 = False
    co1 = False
    co2 = False
    if os.path.exists(path1+image) and os.path.exists(path2+image):
        img = nib.load(path1 + image)
        label = nib.load(path2 + image)

        a = img.get_fdata().shape[0]
        b = img.get_fdata().shape[1]
        c = img.get_fdata().shape[2]

        if a < 35 or a > 71:
            new_a = np.clip(a, 35, 71)
            co0 = True
        if b < 35 or b > 71:
            new_b = np.clip(b, 35, 71)
            co1 = True
        if c < 35 or c > 71:
            new_c = np.clip(c, 35, 71)
            co2 = True

        if not os.path.exists("/out/images"):
            os.makedirs("/out/images")

        if not os.path.exists("/out/labels"):
            os.makedirs("/out/labels")

        if co0 == False and co1 == False and co2 == False:
            print(image + " is normal")
            os.chdir("/out/images/")
            img.to_filename(image)
            os.chdir("/out/labels/")
            label.to_filename(image)

        elif co0 == True and co1 == False and co2 == False:
            new_img = resize_data(img, new_a, b, c)
            new_lbl = resize_data(label, new_a, b, c)
            print(image + " is resized")
            nibimg = nib.Nifti1Image(new_img, np.eye(4))
            os.chdir("/out/images/")
            nibimg.to_filename(image)
            niblab = nib.Nifti1Image(new_lbl, np.eye(4))
            os.chdir("/out/labels/")
            niblab.to_filename(image)
            x = nib.load("/out/images/" + image)
            print(x.get_fdata().shape, end="")
            x = nib.load("/out/labels/" + image)
            print(" : " + str(x.get_fdata().shape))

        elif co0 == False and co1 == True and co2 == False:
            new_img = resize_data(img, a, new_b, c)
            new_lbl = resize_data(label, a, new_b, c)
            print(image + " is resized")
            nibimg = nib.Nifti1Image(new_img, np.eye(4))
            os.chdir("/out/images/")
            nibimg.to_filename(image)
            niblab = nib.Nifti1Image(new_lbl, np.eye(4))
            os.chdir("/out/labels/")
            niblab.to_filename(image)
            x = nib.load("/out/images/" + image)
            print(x.get_fdata().shape, end="")
            x = nib.load("/out/labels/" + image)
            print(" : " + str(x.get_fdata().shape))

        elif co0 == False and co1 == False and co2 == True:
            new_img = resize_data(img, a, b, new_c)
            new_lbl = resize_data(label, a, b, new_c)
            print(image + " is resized")
            nibimg = nib.Nifti1Image(new_img, np.eye(4))
            os.chdir("/out/images/")
            nibimg.to_filename(image)
            niblab = nib.Nifti1Image(new_lbl, np.eye(4))
            os.chdir("/out/labels/")
            niblab.to_filename(image)
            x = nib.load("/out/images/" + image)
            print(x.get_fdata().shape, end="")
            x = nib.load("/out/labels/" + image)
            print(" : " + str(x.get_fdata().shape))

        elif co0 == True and co1 == True and co2 == False:
            new_img = resize_data(img, new_a, new_b, c)
            new_lbl = resize_data(label, new_a, new_b, c)
            print(image + " is resized")
            nibimg = nib.Nifti1Image(new_img, np.eye(4))
            os.chdir("/out/images/")
            nibimg.to_filename(image)
            niblab = nib.Nifti1Image(new_lbl, np.eye(4))
            os.chdir("/out/labels/")
            niblab.to_filename(image)
            x = nib.load("/out/images/" + image)
            print(x.get_fdata().shape, end="")
            x = nib.load("/out/labels/" + image)
            print(" : " + str(x.get_fdata().shape))

        elif co0 == True and co1 == False and co2 == True:
            new_img = resize_data(img, new_a, b, new_c)
            new_lbl = resize_data(label, new_a, b, new_c)
            print(image + " is resized")
            nibimg = nib.Nifti1Image(new_img, np.eye(4))
            os.chdir("/out/images/")
            nibimg.to_filename(image)
            niblab = nib.Nifti1Image(new_lbl, np.eye(4))
            os.chdir("/out/labels/")
            niblab.to_filename(image)
            x = nib.load("/out/images/" + image)
            print(x.get_fdata().shape, end="")
            x = nib.load("/out/labels/" + image)
            print(" : " + str(x.get_fdata().shape))

        elif co0 == False and co1 == True and co2 == True:
            new_img = resize_data(img, a, new_b, new_c)
            new_lbl = resize_data(label, a, new_b, new_c)
            print(image + " is resized")
            nibimg = nib.Nifti1Image(new_img, np.eye(4))
            os.chdir("/out/images/")
            nibimg.to_filename(image)
            niblab = nib.Nifti1Image(new_lbl, np.eye(4))
            os.chdir("/out/labels/")
            niblab.to_filename(image)
            x = nib.load("/out/images/" + image)
            print(x.get_fdata().shape, end="")
            x = nib.load("/out/labels/" + image)
            print(" : " + str(x.get_fdata().shape))

        elif co0 == True and co1 == True and co2 == True:
            new_img = resize_data(img, new_a, new_b, new_c)
            new_lbl = resize_data(label, new_a, new_b, new_c)
            print(image + " is resized")
            nibimg = nib.Nifti1Image(new_img, np.eye(4))
            os.chdir("/out/images/")
            nibimg.to_filename(image)
            niblab = nib.Nifti1Image(new_lbl, np.eye(4))
            os.chdir("/out/labels/")
            niblab.to_filename(image)
            x = nib.load("/out/images/" + image)
            print(x.get_fdata().shape, end="")
            x = nib.load("/out/labels/" + image)
            print(" : " + str(x.get_fdata().shape))

hippocampus_376.nii.gz is normal
hippocampus_165.nii.gz is resized
(35, 49, 35) : (35, 49, 35)
hippocampus_286.nii.gz is normal
hippocampus_152.nii.gz is normal
hippocampus_176.nii.gz is normal
hippocampus_096.nii.gz is resized
(35, 47, 39) : (35, 47, 39)
hippocampus_068.nii.gz is normal
hippocampus_289.nii.gz is normal
hippocampus_260.nii.gz is resized
(35, 53, 35) : (35, 53, 35)
hippocampus_171.nii.gz is resized
(35, 56, 35) : (35, 56, 35)
hippocampus_296.nii.gz is normal
hippocampus_142.nii.gz is normal
hippocampus_375.nii.gz is resized
(35, 54, 35) : (35, 54, 35)
hippocampus_097.nii.gz is resized
(37, 48, 35) : (37, 48, 35)
hippocampus_064.nii.gz is normal
hippocampus_108.nii.gz is normal
hippocampus_070.nii.gz is normal
hippocampus_329.nii.gz is resized
(35, 53, 35) : (35, 53, 35)
hippocampus_107.nii.gz is resized
(35, 55, 35) : (35, 55, 35)
hippocampus_090.nii.gz is normal
hippocampus_092.nii.gz is resized
(38, 49, 35) : (38, 49, 35)
hippocampus_318.nii.gz is resized
(37, 51, 35)

hippocampus_360.nii.gz is resized
(35, 49, 37) : (35, 49, 37)
hippocampus_322.nii.gz is normal
hippocampus_101.nii.gz is resized
(36, 52, 35) : (36, 52, 35)
hippocampus_144.nii.gz is resized
(35, 45, 43) : (35, 45, 43)
hippocampus_311.nii.gz is normal
hippocampus_238.nii.gz is normal
hippocampus_001.nii.gz is normal
hippocampus_261.nii.gz is resized
(36, 58, 35) : (36, 58, 35)
hippocampus_207.nii.gz is resized
(35, 53, 35) : (35, 53, 35)
hippocampus_184.nii.gz is resized
(37, 51, 35) : (37, 51, 35)
hippocampus_044.nii.gz is resized
(38, 48, 35) : (38, 48, 35)
hippocampus_386.nii.gz is normal
hippocampus_290.nii.gz is normal
hippocampus_310.nii.gz is normal
hippocampus_148.nii.gz is resized
(35, 48, 35) : (35, 48, 35)
hippocampus_231.nii.gz is resized
(35, 47, 42) : (35, 47, 42)
hippocampus_178.nii.gz is normal
hippocampus_264.nii.gz is normal
hippocampus_358.nii.gz is resized
(35, 50, 35) : (35, 50, 35)
hippocampus_276.nii.gz is resized
(35, 50, 35) : (35, 50, 35)
hippocampus_363.nii.g

## Final remarks

Congratulations! You have finished Section 1. 

In this section you have inspected a dataset of MRI scans and related segmentations, represented as NIFTI files. We have visualized some slices, and understood the layout of the data. We have inspected file headers to understand what how the image dimensions relate to the physical world and we have understood how to measure our volume. We have then inspected dataset for outliers, and have created a clean set that is ready for consumption by our ML algorithm. 

In the next section you will create training and testing pipelines for a UNet-based machine learning model, run and monitor the execution, and will produce test metrics. This will arm you with all you need to use the model in the clinical context and reason about its performance!